stages:
  - build
  - test

build_job:
  stage: build
  script:
    - apk add --no-cache python3 py3-pip py3-virtualenv
    - python3 -V
    - virtualenv venv
    - . venv/bin/activate
    - pip3 install -r requirements.txt

test_job:
  stage: test
  script:
    - apk add --no-cache python3 py3-pip py3-virtualenv
    - python3 -V
    - virtualenv venv
    - . venv/bin/activate
    - pip3 install -r requirements.txt
    - python3 -m unittest discover tests
